### ISSUE TITLE
Broken wifi

### ISSUE THREAD

**Issue by Stizzie** [dougg0k/gaming_os_tweaker#21]
After run all de-bloat and tweak, the pop up from the taskbar to select a wireless network doesn't work. Windows network setting also broken.

**Comment by dougg0k** [comment]
Yeah, I know about Windows Settings Network , though it's still usable in the control panel. I suppose someone could try to find what exactly causes it to break and make a PR with a comment.

As for the wifi, I didnt do anything to account that someone would still be using wifi when doing this kind of tweaks, since Ethernet should be the default and obvious choice for low latency and reliability.
